import Head from 'next/head';
import React from 'react';
import {
	User,
	useSession,
	useSupabaseClient,
} from '@supabase/auth-helpers-react';
import Link from 'next/link';
import Dashboard from './dashboard';

export default function Home() {
	const session = useSession();
	const supabase = useSupabaseClient();
	const user = session?.user as User;
	const [username, setUsername] = React.useState('');
	const [password, setPassword] = React.useState('');
	const [loading, setLoading] = React.useState(false);

	async function buttonHandler(event: any) {
		event.preventDefault();

		setLoading(true);
		// Reset loading animation
		setTimeout(() => {
			setLoading(false);
		}, 5000);

		// Sign in
		const { data, error } = await supabase.auth.signInWithPassword({
			email: username,
			password: password,
		});
		if (error) {
			alert(error.message);
			setLoading(false);
		}
	}

	return (
		<>
			<Head>
				<title>Tutorworks</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{!session ? (
				<div className='hero min-h-screen bg-base-200'>
					<div className='hero-content flex-col lg:flex-row-reverse'>
						<div className='text-center lg:text-left'>
							<h1 className='text-5xl font-bold'>Login now!</h1>
							<p className='py-6'>
								Provident cupiditate voluptatem et in. Quaerat
								fugiat ut assumenda excepturi exercitationem
								quasi. In deleniti eaque aut repudiandae et a id
								nisi.
							</p>
						</div>
						<div className='card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100'>
							<div className='card-body'>
								<div className='form-control'>
									<label className='label'>
										<span className='label-text'>
											Email
										</span>
									</label>
									<input
										onChange={(e) => {
											setUsername(e.target.value);
										}}
										type='text'
										autoFocus
										placeholder='email'
										className='input input-bordered'
									/>
								</div>
								<div className='form-control'>
									<label className='label'>
										<span className='label-text'>
											Password
										</span>
									</label>
									<input
										onChange={(e) => {
											setPassword(e.target.value);
										}}
										type='password'
										placeholder='password'
										className='input input-bordered'
									/>
									<label className='label text-xs'>
										<Link href='reset-password'>
											Forgot password?
										</Link>
									</label>
								</div>
								<div className='form-control mt-6'>
									<button
										onClick={buttonHandler}
										className={
											loading
												? 'btn btn-primary loading'
												: 'btn btn-primary'
										}
									>
										Login
									</button>
								</div>
								<div>
									<p className='text-center mt-4'>
										<Link href='signup'>
											Don&apos;t have an account?
										</Link>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			) : (
				<Dashboard session={session} user={user} />
			)}
		</>
	);
}
